spring.application.name=news-reader

#??? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/news_reader
spring.datasource.username=news_reader_app
spring.datasource.password=news

spring.jpa.hibernate.ddl-auto=update